apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: vijaykumarvkn/payment-service:latest
        env:
        - name: NODE_ENV
          value: production
        - name: PRODUCT_URL
          value: http://product-service:3002
        - name: PAYMENT_URL
          value: http://payment-service:3004
        ports:
        - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - protocol: TCP
    port: 3004
    targetPort: 3004
  type: ClusterIP
